// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

#include "index.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_index_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_index_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Pair;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_index_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Weight;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_index_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_DocInfo;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_index_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_KwdInfo;
}  // namespace protobuf_index_2eproto
namespace doc_index_proto {
class PairDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Pair>
      _instance;
} _Pair_default_instance_;
class DocInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DocInfo>
      _instance;
} _DocInfo_default_instance_;
class WeightDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Weight>
      _instance;
} _Weight_default_instance_;
class KwdInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<KwdInfo>
      _instance;
} _KwdInfo_default_instance_;
class IndexDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Index>
      _instance;
} _Index_default_instance_;
}  // namespace doc_index_proto
namespace protobuf_index_2eproto {
static void InitDefaultsPair() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::doc_index_proto::_Pair_default_instance_;
    new (ptr) ::doc_index_proto::Pair();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::doc_index_proto::Pair::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Pair =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPair}, {}};

static void InitDefaultsDocInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::doc_index_proto::_DocInfo_default_instance_;
    new (ptr) ::doc_index_proto::DocInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::doc_index_proto::DocInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_DocInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsDocInfo}, {
      &protobuf_index_2eproto::scc_info_Pair.base,}};

static void InitDefaultsWeight() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::doc_index_proto::_Weight_default_instance_;
    new (ptr) ::doc_index_proto::Weight();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::doc_index_proto::Weight::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Weight =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsWeight}, {}};

static void InitDefaultsKwdInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::doc_index_proto::_KwdInfo_default_instance_;
    new (ptr) ::doc_index_proto::KwdInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::doc_index_proto::KwdInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_KwdInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsKwdInfo}, {
      &protobuf_index_2eproto::scc_info_Weight.base,}};

static void InitDefaultsIndex() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::doc_index_proto::_Index_default_instance_;
    new (ptr) ::doc_index_proto::Index();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::doc_index_proto::Index::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_Index =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsIndex}, {
      &protobuf_index_2eproto::scc_info_DocInfo.base,
      &protobuf_index_2eproto::scc_info_KwdInfo.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Pair.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DocInfo.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Weight.base);
  ::google::protobuf::internal::InitSCC(&scc_info_KwdInfo.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Index.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Pair, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Pair, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Pair, beg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Pair, end_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::DocInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::DocInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::DocInfo, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::DocInfo, title_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::DocInfo, content_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::DocInfo, show_url_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::DocInfo, jump_url_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::DocInfo, title_token_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::DocInfo, content_token_),
  6,
  0,
  1,
  2,
  3,
  4,
  5,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Weight, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Weight, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Weight, doc_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Weight, weight_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::KwdInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::KwdInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::KwdInfo, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::KwdInfo, doc_list_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Index, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Index, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Index, forward_index_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::doc_index_proto::Index, inverted_index_),
  ~0u,
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::doc_index_proto::Pair)},
  { 9, 21, sizeof(::doc_index_proto::DocInfo)},
  { 28, 35, sizeof(::doc_index_proto::Weight)},
  { 37, 44, sizeof(::doc_index_proto::KwdInfo)},
  { 46, 53, sizeof(::doc_index_proto::Index)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::doc_index_proto::_Pair_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::doc_index_proto::_DocInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::doc_index_proto::_Weight_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::doc_index_proto::_KwdInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::doc_index_proto::_Index_default_instance_),
};

static void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "index.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

static void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

static void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013index.proto\022\017doc_index_proto\" \n\004Pair\022\013"
      "\n\003beg\030\001 \002(\r\022\013\n\003end\030\002 \002(\r\"\263\001\n\007DocInfo\022\n\n\002"
      "id\030\001 \002(\004\022\r\n\005title\030\002 \002(\t\022\017\n\007content\030\003 \002(\t"
      "\022\020\n\010show_url\030\004 \002(\t\022\020\n\010jump_url\030\005 \002(\t\022*\n\013"
      "title_token\030\006 \002(\0132\025.doc_index_proto.Pair"
      "\022,\n\rcontent_token\030\007 \002(\0132\025.doc_index_prot"
      "o.Pair\"(\n\006Weight\022\016\n\006doc_id\030\001 \002(\004\022\016\n\006weig"
      "ht\030\002 \002(\005\"A\n\007KwdInfo\022\013\n\003key\030\001 \002(\t\022)\n\010doc_"
      "list\030\002 \002(\0132\027.doc_index_proto.Weight\"j\n\005I"
      "ndex\022/\n\rforward_index\030\001 \003(\0132\030.doc_index_"
      "proto.DocInfo\0220\n\016inverted_index\030\002 \002(\0132\030."
      "doc_index_proto.KwdInfo"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 463);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "index.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_index_2eproto
namespace doc_index_proto {

// ===================================================================

void Pair::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Pair::kBegFieldNumber;
const int Pair::kEndFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Pair::Pair()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_index_2eproto::scc_info_Pair.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:doc_index_proto.Pair)
}
Pair::Pair(const Pair& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&beg_, &from.beg_,
    static_cast<size_t>(reinterpret_cast<char*>(&end_) -
    reinterpret_cast<char*>(&beg_)) + sizeof(end_));
  // @@protoc_insertion_point(copy_constructor:doc_index_proto.Pair)
}

void Pair::SharedCtor() {
  ::memset(&beg_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&end_) -
      reinterpret_cast<char*>(&beg_)) + sizeof(end_));
}

Pair::~Pair() {
  // @@protoc_insertion_point(destructor:doc_index_proto.Pair)
  SharedDtor();
}

void Pair::SharedDtor() {
}

void Pair::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Pair::descriptor() {
  ::protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Pair& Pair::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_index_2eproto::scc_info_Pair.base);
  return *internal_default_instance();
}


void Pair::Clear() {
// @@protoc_insertion_point(message_clear_start:doc_index_proto.Pair)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    ::memset(&beg_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&end_) -
        reinterpret_cast<char*>(&beg_)) + sizeof(end_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Pair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:doc_index_proto.Pair)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 beg = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_beg();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &beg_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required uint32 end = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_end();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &end_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:doc_index_proto.Pair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:doc_index_proto.Pair)
  return false;
#undef DO_
}

void Pair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:doc_index_proto.Pair)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 beg = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->beg(), output);
  }

  // required uint32 end = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->end(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:doc_index_proto.Pair)
}

::google::protobuf::uint8* Pair::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:doc_index_proto.Pair)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 beg = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->beg(), target);
  }

  // required uint32 end = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->end(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doc_index_proto.Pair)
  return target;
}

size_t Pair::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:doc_index_proto.Pair)
  size_t total_size = 0;

  if (has_beg()) {
    // required uint32 beg = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->beg());
  }

  if (has_end()) {
    // required uint32 end = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->end());
  }

  return total_size;
}
size_t Pair::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:doc_index_proto.Pair)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required uint32 beg = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->beg());

    // required uint32 end = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->end());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Pair::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:doc_index_proto.Pair)
  GOOGLE_DCHECK_NE(&from, this);
  const Pair* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Pair>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:doc_index_proto.Pair)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:doc_index_proto.Pair)
    MergeFrom(*source);
  }
}

void Pair::MergeFrom(const Pair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:doc_index_proto.Pair)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      beg_ = from.beg_;
    }
    if (cached_has_bits & 0x00000002u) {
      end_ = from.end_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Pair::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:doc_index_proto.Pair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Pair::CopyFrom(const Pair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:doc_index_proto.Pair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Pair::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void Pair::Swap(Pair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Pair::InternalSwap(Pair* other) {
  using std::swap;
  swap(beg_, other->beg_);
  swap(end_, other->end_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Pair::GetMetadata() const {
  protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DocInfo::InitAsDefaultInstance() {
  ::doc_index_proto::_DocInfo_default_instance_._instance.get_mutable()->title_token_ = const_cast< ::doc_index_proto::Pair*>(
      ::doc_index_proto::Pair::internal_default_instance());
  ::doc_index_proto::_DocInfo_default_instance_._instance.get_mutable()->content_token_ = const_cast< ::doc_index_proto::Pair*>(
      ::doc_index_proto::Pair::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DocInfo::kIdFieldNumber;
const int DocInfo::kTitleFieldNumber;
const int DocInfo::kContentFieldNumber;
const int DocInfo::kShowUrlFieldNumber;
const int DocInfo::kJumpUrlFieldNumber;
const int DocInfo::kTitleTokenFieldNumber;
const int DocInfo::kContentTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DocInfo::DocInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_index_2eproto::scc_info_DocInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:doc_index_proto.DocInfo)
}
DocInfo::DocInfo(const DocInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  title_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_title()) {
    title_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.title_);
  }
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_content()) {
    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  show_url_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_show_url()) {
    show_url_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.show_url_);
  }
  jump_url_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_jump_url()) {
    jump_url_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.jump_url_);
  }
  if (from.has_title_token()) {
    title_token_ = new ::doc_index_proto::Pair(*from.title_token_);
  } else {
    title_token_ = NULL;
  }
  if (from.has_content_token()) {
    content_token_ = new ::doc_index_proto::Pair(*from.content_token_);
  } else {
    content_token_ = NULL;
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:doc_index_proto.DocInfo)
}

void DocInfo::SharedCtor() {
  title_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  show_url_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  jump_url_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&title_token_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&title_token_)) + sizeof(id_));
}

DocInfo::~DocInfo() {
  // @@protoc_insertion_point(destructor:doc_index_proto.DocInfo)
  SharedDtor();
}

void DocInfo::SharedDtor() {
  title_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  show_url_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  jump_url_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete title_token_;
  if (this != internal_default_instance()) delete content_token_;
}

void DocInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DocInfo::descriptor() {
  ::protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DocInfo& DocInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_index_2eproto::scc_info_DocInfo.base);
  return *internal_default_instance();
}


void DocInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:doc_index_proto.DocInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      title_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      content_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      show_url_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000008u) {
      jump_url_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(title_token_ != NULL);
      title_token_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(content_token_ != NULL);
      content_token_->Clear();
    }
  }
  id_ = GOOGLE_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool DocInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:doc_index_proto.DocInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string title = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_title()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->title().data(), static_cast<int>(this->title().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "doc_index_proto.DocInfo.title");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string content = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->content().data(), static_cast<int>(this->content().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "doc_index_proto.DocInfo.content");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string show_url = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_show_url()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->show_url().data(), static_cast<int>(this->show_url().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "doc_index_proto.DocInfo.show_url");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string jump_url = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_jump_url()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->jump_url().data(), static_cast<int>(this->jump_url().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "doc_index_proto.DocInfo.jump_url");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .doc_index_proto.Pair title_token = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_title_token()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .doc_index_proto.Pair content_token = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_content_token()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:doc_index_proto.DocInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:doc_index_proto.DocInfo)
  return false;
#undef DO_
}

void DocInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:doc_index_proto.DocInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 id = 1;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->id(), output);
  }

  // required string title = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->title().data(), static_cast<int>(this->title().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.DocInfo.title");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->title(), output);
  }

  // required string content = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.DocInfo.content");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->content(), output);
  }

  // required string show_url = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->show_url().data(), static_cast<int>(this->show_url().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.DocInfo.show_url");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->show_url(), output);
  }

  // required string jump_url = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->jump_url().data(), static_cast<int>(this->jump_url().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.DocInfo.jump_url");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->jump_url(), output);
  }

  // required .doc_index_proto.Pair title_token = 6;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->_internal_title_token(), output);
  }

  // required .doc_index_proto.Pair content_token = 7;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->_internal_content_token(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:doc_index_proto.DocInfo)
}

::google::protobuf::uint8* DocInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:doc_index_proto.DocInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 id = 1;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->id(), target);
  }

  // required string title = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->title().data(), static_cast<int>(this->title().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.DocInfo.title");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->title(), target);
  }

  // required string content = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.DocInfo.content");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->content(), target);
  }

  // required string show_url = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->show_url().data(), static_cast<int>(this->show_url().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.DocInfo.show_url");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->show_url(), target);
  }

  // required string jump_url = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->jump_url().data(), static_cast<int>(this->jump_url().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.DocInfo.jump_url");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->jump_url(), target);
  }

  // required .doc_index_proto.Pair title_token = 6;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->_internal_title_token(), deterministic, target);
  }

  // required .doc_index_proto.Pair content_token = 7;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        7, this->_internal_content_token(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doc_index_proto.DocInfo)
  return target;
}

size_t DocInfo::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:doc_index_proto.DocInfo)
  size_t total_size = 0;

  if (has_title()) {
    // required string title = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->title());
  }

  if (has_content()) {
    // required string content = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  if (has_show_url()) {
    // required string show_url = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->show_url());
  }

  if (has_jump_url()) {
    // required string jump_url = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->jump_url());
  }

  if (has_title_token()) {
    // required .doc_index_proto.Pair title_token = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *title_token_);
  }

  if (has_content_token()) {
    // required .doc_index_proto.Pair content_token = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *content_token_);
  }

  if (has_id()) {
    // required uint64 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->id());
  }

  return total_size;
}
size_t DocInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:doc_index_proto.DocInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000007f) ^ 0x0000007f) == 0) {  // All required fields are present.
    // required string title = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->title());

    // required string content = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());

    // required string show_url = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->show_url());

    // required string jump_url = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->jump_url());

    // required .doc_index_proto.Pair title_token = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *title_token_);

    // required .doc_index_proto.Pair content_token = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *content_token_);

    // required uint64 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->id());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DocInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:doc_index_proto.DocInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const DocInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DocInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:doc_index_proto.DocInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:doc_index_proto.DocInfo)
    MergeFrom(*source);
  }
}

void DocInfo::MergeFrom(const DocInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:doc_index_proto.DocInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 127u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_title();
      title_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.title_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_content();
      content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_show_url();
      show_url_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.show_url_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_jump_url();
      jump_url_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.jump_url_);
    }
    if (cached_has_bits & 0x00000010u) {
      mutable_title_token()->::doc_index_proto::Pair::MergeFrom(from.title_token());
    }
    if (cached_has_bits & 0x00000020u) {
      mutable_content_token()->::doc_index_proto::Pair::MergeFrom(from.content_token());
    }
    if (cached_has_bits & 0x00000040u) {
      id_ = from.id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void DocInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:doc_index_proto.DocInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DocInfo::CopyFrom(const DocInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:doc_index_proto.DocInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DocInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000007f) != 0x0000007f) return false;
  if (has_title_token()) {
    if (!this->title_token_->IsInitialized()) return false;
  }
  if (has_content_token()) {
    if (!this->content_token_->IsInitialized()) return false;
  }
  return true;
}

void DocInfo::Swap(DocInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DocInfo::InternalSwap(DocInfo* other) {
  using std::swap;
  title_.Swap(&other->title_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  content_.Swap(&other->content_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  show_url_.Swap(&other->show_url_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  jump_url_.Swap(&other->jump_url_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(title_token_, other->title_token_);
  swap(content_token_, other->content_token_);
  swap(id_, other->id_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DocInfo::GetMetadata() const {
  protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Weight::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Weight::kDocIdFieldNumber;
const int Weight::kWeightFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Weight::Weight()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_index_2eproto::scc_info_Weight.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:doc_index_proto.Weight)
}
Weight::Weight(const Weight& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&doc_id_, &from.doc_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&weight_) -
    reinterpret_cast<char*>(&doc_id_)) + sizeof(weight_));
  // @@protoc_insertion_point(copy_constructor:doc_index_proto.Weight)
}

void Weight::SharedCtor() {
  ::memset(&doc_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&weight_) -
      reinterpret_cast<char*>(&doc_id_)) + sizeof(weight_));
}

Weight::~Weight() {
  // @@protoc_insertion_point(destructor:doc_index_proto.Weight)
  SharedDtor();
}

void Weight::SharedDtor() {
}

void Weight::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Weight::descriptor() {
  ::protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Weight& Weight::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_index_2eproto::scc_info_Weight.base);
  return *internal_default_instance();
}


void Weight::Clear() {
// @@protoc_insertion_point(message_clear_start:doc_index_proto.Weight)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    ::memset(&doc_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&weight_) -
        reinterpret_cast<char*>(&doc_id_)) + sizeof(weight_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Weight::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:doc_index_proto.Weight)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 doc_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_doc_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &doc_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 weight = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_weight();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:doc_index_proto.Weight)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:doc_index_proto.Weight)
  return false;
#undef DO_
}

void Weight::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:doc_index_proto.Weight)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 doc_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->doc_id(), output);
  }

  // required int32 weight = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->weight(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:doc_index_proto.Weight)
}

::google::protobuf::uint8* Weight::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:doc_index_proto.Weight)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 doc_id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->doc_id(), target);
  }

  // required int32 weight = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->weight(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doc_index_proto.Weight)
  return target;
}

size_t Weight::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:doc_index_proto.Weight)
  size_t total_size = 0;

  if (has_doc_id()) {
    // required uint64 doc_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->doc_id());
  }

  if (has_weight()) {
    // required int32 weight = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->weight());
  }

  return total_size;
}
size_t Weight::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:doc_index_proto.Weight)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required uint64 doc_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->doc_id());

    // required int32 weight = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->weight());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Weight::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:doc_index_proto.Weight)
  GOOGLE_DCHECK_NE(&from, this);
  const Weight* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Weight>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:doc_index_proto.Weight)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:doc_index_proto.Weight)
    MergeFrom(*source);
  }
}

void Weight::MergeFrom(const Weight& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:doc_index_proto.Weight)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      doc_id_ = from.doc_id_;
    }
    if (cached_has_bits & 0x00000002u) {
      weight_ = from.weight_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Weight::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:doc_index_proto.Weight)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Weight::CopyFrom(const Weight& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:doc_index_proto.Weight)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Weight::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void Weight::Swap(Weight* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Weight::InternalSwap(Weight* other) {
  using std::swap;
  swap(doc_id_, other->doc_id_);
  swap(weight_, other->weight_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Weight::GetMetadata() const {
  protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void KwdInfo::InitAsDefaultInstance() {
  ::doc_index_proto::_KwdInfo_default_instance_._instance.get_mutable()->doc_list_ = const_cast< ::doc_index_proto::Weight*>(
      ::doc_index_proto::Weight::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KwdInfo::kKeyFieldNumber;
const int KwdInfo::kDocListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KwdInfo::KwdInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_index_2eproto::scc_info_KwdInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:doc_index_proto.KwdInfo)
}
KwdInfo::KwdInfo(const KwdInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_key()) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.has_doc_list()) {
    doc_list_ = new ::doc_index_proto::Weight(*from.doc_list_);
  } else {
    doc_list_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:doc_index_proto.KwdInfo)
}

void KwdInfo::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  doc_list_ = NULL;
}

KwdInfo::~KwdInfo() {
  // @@protoc_insertion_point(destructor:doc_index_proto.KwdInfo)
  SharedDtor();
}

void KwdInfo::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete doc_list_;
}

void KwdInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* KwdInfo::descriptor() {
  ::protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const KwdInfo& KwdInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_index_2eproto::scc_info_KwdInfo.base);
  return *internal_default_instance();
}


void KwdInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:doc_index_proto.KwdInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      key_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(doc_list_ != NULL);
      doc_list_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool KwdInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:doc_index_proto.KwdInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "doc_index_proto.KwdInfo.key");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .doc_index_proto.Weight doc_list = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_doc_list()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:doc_index_proto.KwdInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:doc_index_proto.KwdInfo)
  return false;
#undef DO_
}

void KwdInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:doc_index_proto.KwdInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string key = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.KwdInfo.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // required .doc_index_proto.Weight doc_list = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_doc_list(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:doc_index_proto.KwdInfo)
}

::google::protobuf::uint8* KwdInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:doc_index_proto.KwdInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string key = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "doc_index_proto.KwdInfo.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // required .doc_index_proto.Weight doc_list = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_doc_list(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doc_index_proto.KwdInfo)
  return target;
}

size_t KwdInfo::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:doc_index_proto.KwdInfo)
  size_t total_size = 0;

  if (has_key()) {
    // required string key = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  if (has_doc_list()) {
    // required .doc_index_proto.Weight doc_list = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *doc_list_);
  }

  return total_size;
}
size_t KwdInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:doc_index_proto.KwdInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string key = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());

    // required .doc_index_proto.Weight doc_list = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *doc_list_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KwdInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:doc_index_proto.KwdInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const KwdInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KwdInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:doc_index_proto.KwdInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:doc_index_proto.KwdInfo)
    MergeFrom(*source);
  }
}

void KwdInfo::MergeFrom(const KwdInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:doc_index_proto.KwdInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_key();
      key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_doc_list()->::doc_index_proto::Weight::MergeFrom(from.doc_list());
    }
  }
}

void KwdInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:doc_index_proto.KwdInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KwdInfo::CopyFrom(const KwdInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:doc_index_proto.KwdInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KwdInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  if (has_doc_list()) {
    if (!this->doc_list_->IsInitialized()) return false;
  }
  return true;
}

void KwdInfo::Swap(KwdInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KwdInfo::InternalSwap(KwdInfo* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(doc_list_, other->doc_list_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata KwdInfo::GetMetadata() const {
  protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Index::InitAsDefaultInstance() {
  ::doc_index_proto::_Index_default_instance_._instance.get_mutable()->inverted_index_ = const_cast< ::doc_index_proto::KwdInfo*>(
      ::doc_index_proto::KwdInfo::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Index::kForwardIndexFieldNumber;
const int Index::kInvertedIndexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Index::Index()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_index_2eproto::scc_info_Index.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:doc_index_proto.Index)
}
Index::Index(const Index& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      forward_index_(from.forward_index_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_inverted_index()) {
    inverted_index_ = new ::doc_index_proto::KwdInfo(*from.inverted_index_);
  } else {
    inverted_index_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:doc_index_proto.Index)
}

void Index::SharedCtor() {
  inverted_index_ = NULL;
}

Index::~Index() {
  // @@protoc_insertion_point(destructor:doc_index_proto.Index)
  SharedDtor();
}

void Index::SharedDtor() {
  if (this != internal_default_instance()) delete inverted_index_;
}

void Index::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Index::descriptor() {
  ::protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Index& Index::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_index_2eproto::scc_info_Index.base);
  return *internal_default_instance();
}


void Index::Clear() {
// @@protoc_insertion_point(message_clear_start:doc_index_proto.Index)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  forward_index_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(inverted_index_ != NULL);
    inverted_index_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Index::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:doc_index_proto.Index)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .doc_index_proto.DocInfo forward_index = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_forward_index()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .doc_index_proto.KwdInfo inverted_index = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_inverted_index()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:doc_index_proto.Index)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:doc_index_proto.Index)
  return false;
#undef DO_
}

void Index::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:doc_index_proto.Index)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .doc_index_proto.DocInfo forward_index = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->forward_index_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->forward_index(static_cast<int>(i)),
      output);
  }

  cached_has_bits = _has_bits_[0];
  // required .doc_index_proto.KwdInfo inverted_index = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_inverted_index(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:doc_index_proto.Index)
}

::google::protobuf::uint8* Index::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:doc_index_proto.Index)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .doc_index_proto.DocInfo forward_index = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->forward_index_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->forward_index(static_cast<int>(i)), deterministic, target);
  }

  cached_has_bits = _has_bits_[0];
  // required .doc_index_proto.KwdInfo inverted_index = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_inverted_index(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doc_index_proto.Index)
  return target;
}

size_t Index::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:doc_index_proto.Index)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required .doc_index_proto.KwdInfo inverted_index = 2;
  if (has_inverted_index()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *inverted_index_);
  }
  // repeated .doc_index_proto.DocInfo forward_index = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->forward_index_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->forward_index(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Index::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:doc_index_proto.Index)
  GOOGLE_DCHECK_NE(&from, this);
  const Index* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Index>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:doc_index_proto.Index)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:doc_index_proto.Index)
    MergeFrom(*source);
  }
}

void Index::MergeFrom(const Index& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:doc_index_proto.Index)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  forward_index_.MergeFrom(from.forward_index_);
  if (from.has_inverted_index()) {
    mutable_inverted_index()->::doc_index_proto::KwdInfo::MergeFrom(from.inverted_index());
  }
}

void Index::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:doc_index_proto.Index)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Index::CopyFrom(const Index& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:doc_index_proto.Index)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Index::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->forward_index())) return false;
  if (has_inverted_index()) {
    if (!this->inverted_index_->IsInitialized()) return false;
  }
  return true;
}

void Index::Swap(Index* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Index::InternalSwap(Index* other) {
  using std::swap;
  CastToBase(&forward_index_)->InternalSwap(CastToBase(&other->forward_index_));
  swap(inverted_index_, other->inverted_index_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Index::GetMetadata() const {
  protobuf_index_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_index_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace doc_index_proto
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::doc_index_proto::Pair* Arena::CreateMaybeMessage< ::doc_index_proto::Pair >(Arena* arena) {
  return Arena::CreateInternal< ::doc_index_proto::Pair >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::doc_index_proto::DocInfo* Arena::CreateMaybeMessage< ::doc_index_proto::DocInfo >(Arena* arena) {
  return Arena::CreateInternal< ::doc_index_proto::DocInfo >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::doc_index_proto::Weight* Arena::CreateMaybeMessage< ::doc_index_proto::Weight >(Arena* arena) {
  return Arena::CreateInternal< ::doc_index_proto::Weight >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::doc_index_proto::KwdInfo* Arena::CreateMaybeMessage< ::doc_index_proto::KwdInfo >(Arena* arena) {
  return Arena::CreateInternal< ::doc_index_proto::KwdInfo >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::doc_index_proto::Index* Arena::CreateMaybeMessage< ::doc_index_proto::Index >(Arena* arena) {
  return Arena::CreateInternal< ::doc_index_proto::Index >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
